### ISSUE TITLE
Error: fatal: bad object ac7ed0108181239e44712926a3582ca96902bc68

### ISSUE THREAD

**Issue by securestep9** [tayfun/flake8-your-pr#3]
trying to run this action on a PR produces an error:
++ grep '\.py$'
fatal: bad object ac7ed0108181239e44712926a3582ca96902bc68

**Comment by Athanasius** [comment]
Are you using `checkout@v2` as first step?  It defaults to `git fetch ... --depth=1` which caused just such an issue for me.  Easily work-around though:

```yml
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```
That makes it *not* do that, but fetch the entire history instead.
