### ISSUE TITLE
provide new documentation as main.workflow is obsolete

### ISSUE THREAD

**Issue by valentijnscholten** [tayfun/flake8-your-pr#5]
the main.workflow way of configuring actions no longer works, you need something like the below in a `.github/workflows/flake8yourpr.yml`

```
name: Flake8 your PR
on: [pull_request]
jobs:
  flake8-your-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: tayfun/flake8-your-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
